site_name: MOD Standards
site_description: MOD Standards
site_author: MOD
site_url: https://modstandards.github.io
dev_addr: 0.0.0.0:8000

repo_name: 'MOD-Standards'
repo_url: 'https://github.com/defencedigital/mod-standards.git'

docs_dir: 'content'
edit_uri: 'edit/source/docs/content/'

theme:
  name: 'material'
  custom_dir: 'theme'
  language: en
  include_sidebar: true
  #favicon: assets/img/icon.png
  #logo: assets/img/logo.png
  feature:
    tabs: false
  font:
    text: Ariel'

copyright: "Copyright &copy; MOD"

extra_css:
  - assets/styles/extra.css
  - assets/styles/atom-one-light.css # HightlightJS's CSS theme
  - assets/styles/govuk-frontend-3.14.0.min.css # HightlightJS's CSS theme
  
extra_javascript:
  - assets/js/hljs/highlight.pack.js # Download from https://highlightjs.org/download/ and enable YAML, TOML and Dockerfile
  - assets/js/extra.js
  

plugins:
  - search
  - exclude:
      glob:
        - "**/include-*.md"

# https://squidfunk.github.io/mkdocs-material/extensions/admonition/
# https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      use_pygments: false # hljs is used instead of pygment for TOML highlighting support
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.snippets:
      check_paths: true
  - toc:
      permalink: true

# Page tree
nav:
  - 'Welcome': 'index.md'
  - 'Blog Posts': 'Blog.md'
  - 'GitHub Actions':
      - 'Docker Deployment' : 'actions/Docker-Deployment.md'
  - 'Ruby Gems':
      - 'DeepHealthCheck': 'ruby-gems/DeepHealthCheck.md'
      - 'DelayedJob Metrics' : 'ruby-gems/DelayedJobMetrics.md'
      - 'FluentD Plugins' :
          - 'Docker Metadata': 'ruby-gems/DockerMetadata.md'
          - 'Empty Keys': 'ruby-gems/EmptyKeys.md'
          - 'Key-Value Parser': 'ruby-gems/Key-ValueParser.md'
          - 'Record Splitter': 'ruby-gems/RecordSplitter.md'
      - 'IRBTracker' : 'ruby-gems/IRBTracker.md'
      - 'RabbitMQ Client' : 'ruby-gems/RabbitMQ.md'
      - 'Swarm Orca' : 'ruby-gems/Orca.md'
  - 'Security':
      - 'Patching': 'security/patching.md'
      - 'Policy document': 'digital/policy1.md'
  #- 'PoC':
